<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-O64J0D3" failures="1" tests="12" name="Default test" time="143.217" errors="0" timestamp="2025-05-13T22:58:24 IST">
  <testcase classname="test.Motsop.SignIn" name="EmptyUserEmptyPassword" time="4.506"/>
  <testcase classname="test.Motsop.SignIn" name="EmptyUserValidPassword" time="4.856"/>
  <testcase classname="test.Motsop.SignIn" name="InvalidMailInvalidPassword" time="4.859"/>
  <testcase classname="test.Motsop.SignIn" name="InvalidMailValidPassword" time="5.095"/>
  <testcase classname="test.Motsop.SignIn" name="InvalidMobileInvalidPassword" time="4.745"/>
  <testcase classname="test.Motsop.SignIn" name="InvalidMobileValidPassword1" time="5.074"/>
  <testcase classname="test.Motsop.SignIn" name="InvalidMobileValidPassword2" time="4.723"/>
  <testcase classname="test.Motsop.SignIn" name="InvalidMobileValidPassword3" time="5.197"/>
  <testcase classname="test.Motsop.SignIn" name="ValidMailEmptyPassword" time="4.91"/>
  <testcase classname="test.Motsop.SignIn" name="ValidMailInvalidPassword" time="5.011"/>
  <testcase classname="test.Motsop.SignIn" name="ValidMailValidPassword" time="5.203"/>
  <testcase classname="test.Motsop.SignIn" name="validMobileValidPassword" time="4.966">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at test.Motsop.SignIn.validMobileValidPassword(SignIn.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- validMobileValidPassword -->
</testsuite> <!-- Default test -->
